version: 2

workflows:
  version: 2
  mackup:
    jobs:
      - nose-2.7
      - install-2.7
      - flake8-2.7
      - mdl

jobs:
  nose-2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: make test
      - run: codecov

  install-2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help

  flake8-2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 mackup

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .
